#!/bin/bash

# Old and useless code
# Causes issue if you try to connect 30+ seconds later


if [ "--h" == "$*" ] || [ "--help" == "$*" ] || [ -z "$*" ] ; then
	mosh
	exit
fi

DIR=/var/tmp/mosh-sessions/
mkdir -p "$DIR"
ARG="$*"
MD5=`echo "$ARG" | md5sum`
MD5=${MD5:0:20}

FILE=$DIR$MD5

if [ -f "$FILE" ]; then
	RAND_FILE="$FILE.$RANDOM"
	mv $FILE $RAND_FILE
fi

touch $FILE
chmod 700 $FILE

(
	NEW_SESSION=`mosh --get "$@" 2>/dev/null`
	echo "$NEW_SESSION" | tee $FILE 1>/dev/null
) &

if [ -z "$RAND_FILE" ]; then
	mosh "$@"
else
	created=`stat -c %Y $RAND_FILE`
	now=`date +"%s"`
	diff=$(($now-$created))
	if [ $diff > 30]; then
		mosh "$@"
	else
		$RAND_FILE
	fi
	rm $RAND_FILE
fi